import { callClaude } from "../claude";

const SYSTEM_PROMPT = `You are the Ethics Review Agent for Voz. You run AFTER listing, pricing, and storefront are generated, and BEFORE publish.

Your job: review the complete generated listing for three failure modes:

1. CULTURAL MISREPRESENTATION — does the description accurately reflect the tradition? Are cultural terms used correctly? Flag stereotyping or flattening (e.g., conflating Mexican regional traditions, generic "tribal" labels).

2. ARTISAN FAIRNESS — is the recommended price at or above a fair handmade labor rate for the described technique? Flag if price_recommended underprices skilled work (e.g., hand-loomed textile under $40 is almost always unfair).

3. CLAIMS ACCURACY — does the listing invent materials, origins, or provenance not supported by the transcript? Flag fabricated heritage claims.

Output ONLY valid JSON:
{
  "status": "approve" | "revise" | "block",
  "issues": [
    {"severity": "low|medium|high", "category": "cultural|fairness|claims", "note": "string", "suggested_fix": "string or null"}
  ],
  "revised_fields": { }
}

Bias toward "approve" unless there is a concrete issue. Do NOT block for stylistic preferences. Only "block" for clearly fabricated heritage claims or severely unfair pricing (<50% of fair rate).`;

export const ETHICS_FALLBACK = {
  status: "approve",
  issues: [] as unknown[],
  revised_fields: {} as Record<string, unknown>,
};

export async function runEthicsAgent(payload: {
  listing: unknown;
  pricing: unknown;
  transcript: string;
  slug: string;
}): Promise<string> {
  const { listing, pricing, transcript, slug } = payload;

  const userContent = `Review this listing for cultural accuracy, artisan fairness, and claims accuracy.

SLUG: ${slug}

TRANSCRIPT (translated to English):
${transcript}

LISTING (generated by Listing Agent):
${JSON.stringify(listing, null, 2)}

PRICING (generated by Pricing Agent):
${JSON.stringify(pricing, null, 2)}

Produce the ethics review JSON now.`;

  return callClaude({
    systemPrompt: SYSTEM_PROMPT,
    userContent,
    maxTokens: 1024,
  });
}
